version: 2
project_name: hydrate

before:
  hooks:
    - go mod tidy

builds:
  - id: hydrate
    main: ./cmd/hydrate
    binary: hydrate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/diomonogatari/hydrate-cli/internal/cli.version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - src: docs/*

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  # Create a draft release to review before publishing.
  draft: true
